version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mi-backend
    ports:
      - "3001:5000"
    environment:
      - NODE_ENV=production  # CAMBIO: development → production
      - PORT=5000
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: mi-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${RAILWAY_PUBLIC_DOMAIN_BACKEND}  # CAMBIO CRÍTICO
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge